
import com.mysql.jdbc.Connection;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import net.proteanit.sql.DbUtils;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author user
 */
public class AllStudent extends javax.swing.JFrame {
    
    Connection con = null;
    Statement stmt = null;
    ResultSet rs = null;
    

    /**
     * Creates new form AllStudent
     */
    public AllStudent() {
        initComponents();
        con = databaseConnection.connection();
        showRecord();
    }
    public void showRecord(){
    try{
    stmt = (Statement) con.createStatement();
    if(gradeA.getSelectedItem().equals("All")){
        String query = "SELECT * FROM student";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
    }
    catch(Exception e){
    System.out.println(e);
    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox2 = new javax.swing.JComboBox<>();
        mainmenu1 = new javax.swing.JButton();
        grade = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        gradeA = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        view = new javax.swing.JTable();
        mainmenu2 = new javax.swing.JButton();
        mainmenu3 = new javax.swing.JButton();
        edit = new javax.swing.JButton();

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        mainmenu1.setBackground(new java.awt.Color(255, 204, 204));
        mainmenu1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        mainmenu1.setText("MAIN MENU");
        mainmenu1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenu1ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        grade.setBackground(new java.awt.Color(0, 102, 153));
        grade.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel1.setText("Student");

        gradeA.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        gradeA.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "All", "1A", "1B", "1C", "2A", "2B", "3A", "3B", "3C", "4A", "5A", "5B", "6A", "7A", "7B", "8A", "9A", "10A", "10B", "11A", "11B", "11C" }));
        gradeA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeAActionPerformed(evt);
            }
        });

        view.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(view);

        mainmenu2.setBackground(new java.awt.Color(255, 204, 204));
        mainmenu2.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        mainmenu2.setText("MAIN MENU");
        mainmenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenu2ActionPerformed(evt);
            }
        });

        mainmenu3.setBackground(new java.awt.Color(255, 204, 204));
        mainmenu3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        mainmenu3.setText("MAIN MENU");
        mainmenu3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mainmenu3ActionPerformed(evt);
            }
        });

        edit.setBackground(new java.awt.Color(255, 204, 204));
        edit.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        edit.setText("EDIT/ADD");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gradeLayout = new javax.swing.GroupLayout(grade);
        grade.setLayout(gradeLayout);
        gradeLayout.setHorizontalGroup(
            gradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradeLayout.createSequentialGroup()
                .addGap(230, 230, 230)
                .addComponent(gradeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradeLayout.createSequentialGroup()
                .addContainerGap(30, Short.MAX_VALUE)
                .addGroup(gradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradeLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addGroup(gradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(mainmenu3)
                            .addComponent(edit))
                        .addGap(15, 15, 15))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradeLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(23, 23, 23))))
            .addGroup(gradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gradeLayout.createSequentialGroup()
                    .addGap(208, 208, 208)
                    .addComponent(mainmenu2)
                    .addContainerGap(209, Short.MAX_VALUE)))
        );
        gradeLayout.setVerticalGroup(
            gradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradeLayout.createSequentialGroup()
                .addGroup(gradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradeLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(gradeA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(gradeLayout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(mainmenu3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(edit)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(gradeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(gradeLayout.createSequentialGroup()
                    .addGap(275, 275, 275)
                    .addComponent(mainmenu2)
                    .addContainerGap(275, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(grade, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void gradeAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeAActionPerformed
        // TODO add your handling code here:
        
        try{
        stmt = (Statement) con.createStatement();
        
        if(gradeA.getSelectedItem().equals("All"))
        {
        String query = "SELECT * FROM student";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("1A"))
        {
        String query = "SELECT * FROM student WHERE grade='1A'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("1B"))
        {
        String query = "SELECT * FROM student WHERE grade='1B'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("1C"))
        {
        String query = "SELECT * FROM student WHERE grade='1C'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("2A"))
        {
        String query = "SELECT * FROM student WHERE grade='2A'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("2B"))
        {
        String query = "SELECT * FROM student WHERE grade='2B'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("3A"))
        {
        String query = "SELECT * FROM student WHERE grade='3A'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("3B"))
        {
        String query = "SELECT * FROM student WHERE grade='3B'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("3C"))
        {
        String query = "SELECT * FROM student WHERE grade='3C'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        
        if(gradeA.getSelectedItem().equals("4A"))
        {
        String query = "SELECT * FROM student WHERE grade='4A'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("5A"))
        {
        String query = "SELECT * FROM student WHERE grade='5A'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("5B"))
        {
        String query = "SELECT * FROM student WHERE grade='5B'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("6A"))
        {
        String query = "SELECT * FROM student WHERE grade='6A'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("7A"))
        {
        String query = "SELECT * FROM student WHERE grade='7A'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("7B"))
        {
        String query = "SELECT * FROM student WHERE grade='7B'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("8A"))
        {
        String query = "SELECT * FROM student WHERE grade='8A'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("9A"))
        {
        String query = "SELECT * FROM student WHERE grade='9A'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("10A"))
        {
        String query = "SELECT * FROM student WHERE grade='1A'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("10B"))
        {
        String query = "SELECT * FROM student WHERE grade='10A'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("11A"))
        {
        String query = "SELECT * FROM student WHERE grade='11A'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("11B"))
        {
        String query = "SELECT * FROM student WHERE grade='11B'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        
        if(gradeA.getSelectedItem().equals("11C"))
        {
        String query = "SELECT * FROM student WHERE grade='11C'";
        ResultSet rs = stmt.executeQuery(query);
        view.setModel(DbUtils.resultSetToTableModel(rs));
       }
        }
        catch(Exception e){
        System.out.println(e);
        }
    }//GEN-LAST:event_gradeAActionPerformed

    private void mainmenu1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenu1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainmenu1ActionPerformed

    private void mainmenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenu2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mainmenu2ActionPerformed

    private void mainmenu3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mainmenu3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        Home view = new Home();
        view.setVisible(true);
    }//GEN-LAST:event_mainmenu3ActionPerformed

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        // TODO add your handling code here:
        
        setVisible(false);
        Student view = new Student();
        view.setVisible(true);
    }//GEN-LAST:event_editActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AllStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AllStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AllStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AllStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AllStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton edit;
    private javax.swing.JPanel grade;
    private javax.swing.JComboBox<String> gradeA;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mainmenu1;
    private javax.swing.JButton mainmenu2;
    private javax.swing.JButton mainmenu3;
    private javax.swing.JTable view;
    // End of variables declaration//GEN-END:variables
}
